
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wagnerrdemorais/microservice-repo
          search-paths: fornecedor
          default-label: main