
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/wagner/workspace/courses/alura/microsservicos/microsservices-repo